// logical operator are used to combine and check the boolean conditions 

//  AND = &&
//  OR = ||
//  NOT = !


// EQUALITY OPERATORS 

// 1 = IS AN ASSIGNMENT OPERATOR USED TO ASIGN THE VALUE TO A VARIABLE 
// 2 == COMPARES IF THE VALUES ARE EQUALS 
// 3 === SRICTLY EQUALS COMPARES IF THE VALUES AND DATATYPES ARE SAME 
// 4 != COMPARES IF VALUES ARE NOT EQUAL 
// 5 !== COMPARES IF THE VALUES AND THE DATATYPES ARE NOT EQUAL 
